# frozen_string_literal: true

source 'https://rubygems.org' do
  gem 'cucumber', '~> 2.4'
  gem 'rspec-expectations'
  gem 'aws-sdk-sns'
  gem 'aws-sdk-sqs'
  gem 'nokogiri'
  gem 'rest-assured', '~> 4.0.0'
  gem 'rest-client'
  gem 'rubocop'
  gem 'sqlite3'
  gem 'process-helper'
end
